name: loon
description: Loon is a reactive collection data store for Dart & Flutter.
version: 5.6.1
homepage: https://github.com/danReynolds/loon

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  path: ^1.8.3
  path_provider: ^2.1.5
  web: ^1.1.0
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  